### ISSUE TITLE
func is not a function

### ISSUE THREAD

**Issue by si458** [Ylianst/Authenticode-JS#4]
```
TypeError: func is not a function
    at C:\Users\sas_2\Documents\Developer\ourbackups\node_modules\authenticode-js\authenticode.js:1557:32
    at IncomingMessage.<anonymous> (C:\Users\sas_2\Documents\Developer\ourbackups\node_modules\authenticode-js\authenticode.js:1590:45)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by si458** [comment]
found the issue, indeed func for the function `obj.sign` is undefined
i have to pass a function, which isnt explained in the readme
`exehandler.sign(cert, { out: 'windowsexecutable-signed.exe', time: "http://timestamp.sectigo.com" }, (error) => { if (error) { console.error(error); } else { console.log('complete'); } });`
